pool:
  vmImage: "windows-2019"
jobs:
  - job: "windows_msvc_conan"
    strategy:
      matrix:
        static:
          conan.shared: "False"
        shared:
          conan.shared: "True"
    steps:
      - bash: choco install pkgconfiglite
        displayName: "Install pkg-config"
      - bash: python -m pip install conan
        displayName: "Install Conan"
      - bash: git submodule update --init --recursive
        displayName: "Fetch git submodules"
      - bash: conan profile detect
        displayName: "Detect Conan profile"
      - bash: conan build -o "&:with_tests=True" -o "&:shared=$(conan.shared)" .
        displayName: "Build with Conan"
